language: php
sudo: required

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.2'

before_script:
#  - pecl install swoole
#  - printf "\n" | pecl install imagick
#  - phpenv config-add php-ext.ini
  - composer update
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - php -i|grep include_path
  - ls -la --color /home/travis/.phpenv/versions/$(phpenv version-name)/share/pear

script:
  - vendor/bin/phpcs --extensions=php ./
#  - php --ri swoole
#  - bash run-scripts
