language: php
sudo: required

php:
  - '5.5'
  - '5.6'
  - '7.0'

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'

before_script:
  - pecl install swoole
  - phpenv config-add php-ext.ini
  - phpenv rehash

script:
  - php --ri swoole
  - bash run-scripts
