language: php
sudo: required

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

services:
  - redis-server

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.2'

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/pecl_cache

before_script:
  - pecl channel-update pecl.php.net
  - bash ci-pecl-install swoole
#  - pecl install swoole
#  - printf "\n" | pecl install imagick
#  - phpenv config-add php-ext.ini
  - composer update
#  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
#  - php -i|grep include_path
#  - ls -la --color /home/travis/.phpenv/versions/$(phpenv version-name)/share/pear
  - php -i|grep -A5 redis

script:
  - vendor/bin/phpcs --extensions=php ./
#  - php --ri swoole
#  - bash run-scripts
