language: php
sudo: required

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.2'

before_script:
  - pecl install swoole
  - printf "\n" | pecl install imagick
  - phpenv config-add php-ext.ini
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs
  - php --ri swoole
  - bash run-scripts
